include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
    unreachable_switch_default: ignore
    unused_element: ignore
    unused_field: ignore

linter:
  rules:
    unnecessary_library_name: false
